import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * The docs' sidebar follows the docs folder: a folder is a section, named and
 * ordered by its _category_.json, and a page's place in it is its
 * sidebar_position. Adding a page is adding a file.
 */
const sidebars: SidebarsConfig = {
  docsSidebar: [{ type: 'autogenerated', dirName: '.' }],
};

export default sidebars;
